// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATAwPmkhEezHHfjBNg5J9iQQ_eWX2YBww',
    appId: '1:641473783215:web:64d2793dc7eceea3ab7b5a',
    messagingSenderId: '641473783215',
    projectId: 'duricare',
    authDomain: 'duricare.firebaseapp.com',
    storageBucket: 'duricare.firebasestorage.app',
    measurementId: 'G-HEV1ZLJ940',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8yHDyJ0_4kIjHUUE24P-M24RkAsyUYz0',
    appId: '1:641473783215:android:775a4b74f04ef676ab7b5a',
    messagingSenderId: '641473783215',
    projectId: 'duricare',
    storageBucket: 'duricare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_2XvE2_QVLvtEMos1_ByN7MWkkAEYbzE',
    appId: '1:641473783215:ios:279615f27749a660ab7b5a',
    messagingSenderId: '641473783215',
    projectId: 'duricare',
    storageBucket: 'duricare.firebasestorage.app',
    iosBundleId: 'com.example.duriCare',
  );
}
